import Image from "next/image";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { Navbar } from "@/components/Navbar";
import { ReminderBar } from "@/components/ReminderBar";
import { useState } from "react";
import { MedicationContainer } from "@/components/reminders/MedicationContainer";
import { DailyRoutineContainer } from "@/components/reminders/DailyRoutineContainer";
import { AppointmentContainer } from "@/components/reminders/AppointmentContainer";

export default function Aides() {
  const [selectedOption, setSelectedOption] = useState("medication");
  const [userAddr, setUserAddr] = useState();

  return (
    <>
      <Head>
        <title>Me, Myself & A.I | Aides</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* @ts-ignore */}
        <Navbar noSignUp={true} />
        <ReminderBar setOption={setSelectedOption} option={selectedOption} />

        <div className={styles.userInput}>
          <input
            placeholder="User Address"
            // @ts-ignore
            onChange={(e) => setUserAddr(e.target.value)}
          />
        </div>

        {selectedOption == "medication" && (
          <MedicationContainer aides={true} user={userAddr} />
        )}

        {selectedOption == "daily routines" && (
          // @ts-ignore
          <DailyRoutineContainer aides={true} user={userAddr} />
        )}
        {selectedOption == "appointments" && (
          // @ts-ignore
          <AppointmentContainer aides={true} user={userAddr} />
        )}
      </main>
    </>
  );
}
