import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { Navbar } from "@/components/Navbar";
import { ReminderBar } from "@/components/ReminderBar";
import { useState } from "react";
import { MedicationContainer } from "@/components/reminders/MedicationContainer";
import { DailyRoutineContainer } from "@/components/reminders/DailyRoutineContainer";
import { AppointmentContainer } from "@/components/reminders/AppointmentContainer";

export default function Landing() {
  const [selectedOption, setSelectedOption] = useState("medication");

  return (
    <>
      <Head>
        <title>Me, Myself & A.I | UpKeeps</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* @ts-ignore */}
        <Navbar noSignUp={true} />
        <ReminderBar setOption={setSelectedOption} option={selectedOption} />
        {/* @ts-ignore */}
        {selectedOption == "medication" && <MedicationContainer />}
        {/* @ts-ignore */}
        {selectedOption == "daily routines" && <DailyRoutineContainer />}
        {/* @ts-ignore */}
        {selectedOption == "appointments" && <AppointmentContainer />}
      </main>
    </>
  );
}
